### ISSUE TITLE
FirstIndex / LastIndex Wrong Behavior When Comparing Structs

### ISSUE THREAD

**Issue by vinicius-trev** [AlexanderAgd/CLIST#1]
Hi all,

I recently discovered an issue related to the comparison statement in both `CList_FirstIndex_` and `CList_LastIndex_`. 

When comparing structs that have a zeroed byte the functions do not behave like expected since the comparison is done string-like.

The simplest solution to this bug would be changing the `strncmp` to `memcmp` in both lines: https://github.com/AlexanderAgd/CLIST/blob/master/clist.c#L186
https://github.com/AlexanderAgd/CLIST/blob/master/clist.c#L201

**Comment by AlexanderAgd** [comment]
Yes correct, fixed, Thank you!
